<?php

/**
* Cassandra Helper for FuelPHP
*
* @package Cassandra
* @version 0.2
*/

$GLOBALS['THRIFT_ROOT'] = __DIR__.'/classes/lib/thrift';
if (! isset($GLOBALS['THRIFT_AUTOLOAD'])) {
    $GLOBALS['THRIFT_AUTOLOAD'] = array();
}

Autoloader::add_core_namespace('Cassandra');

Autoloader::add_classes(array(
  'Cassandra\\Cassandra_Model' => __DIR__.'/classes/model.php',
  'Cassandra\\Cassandra' => __DIR__.'/classes/cassandra.php',
  
  // phpcassa
  'phpcassa\\ColumnFamily' => __DIR__.'/classes/lib/phpcassa/ColumnFamily.php',
  'phpcassa\\ColumnSlice' => __DIR__.'/classes/lib/phpcassa/ColumnSlice.php',
  'phpcassa\\UUID' => __DIR__.'/classes/lib/phpcassa/UUID.php',
  'phpcassa\\Batch\\CfMutator' => __DIR__.'/classes/lib/phpcassa/Batch/CfMutator.php',
  'phpcassa\\Batch\\Mutator' => __DIR__.'/classes/lib/phpcassa/Batch/Mutator.php',
  'phpcassa\\Connection\\ConnectionPool' => __DIR__.'/classes/lib/phpcassa/Connection/ConnectionPool.php',
  'phpcassa\\Connection\\ConnectionWrapper' => __DIR__.'/classes/lib/phpcassa/Connection/ConnectionWrapper.php',
  'phpcassa\\Connection\\MaxRetriesException' => __DIR__.'/classes/lib/phpcassa/Connection/MaxRetriesException.php',
  'phpcassa\\Connection\\NoServerAvailable' => __DIR__.'/classes/lib/phpcassa/Connection/NoServerAvailable.php',
  'phpcassa\\Index\\IndexClause' => __DIR__.'/classes/lib/phpcassa/Index/IndexClause.php',
  'phpcassa\\Index\\IndexExpression' => __DIR__.'/classes/lib/phpcassa/Index/IndexExpression.php',
  'phpcassa\\Iterator\\ColumnFamilyIterator' => __DIR__.'/classes/lib/phpcassa/Iterator/ColumnFamilyIterator.php',
  'phpcassa\\Iterator\\IndexedColumnFamilyIterator' => __DIR__.'/classes/lib/phpcassa/Iterator/IndexedColumnFamilyIterator.php',
  'phpcassa\\Iterator\\RangeColumnFamilyIterator' => __DIR__.'/classes/lib/phpcassa/Iterator/RangeColumnFamilyIterator.php',
  'phpcassa\\Schema\\DataType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType.php',
  'phpcassa\\Schema\\StrategyClass' => __DIR__.'/classes/lib/phpcassa/Schema/StrategyClass.php',
  'phpcassa\\Schema\\DataType\\AsciiType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/AsciiType.php',
  'phpcassa\\Schema\\DataType\\BooleanType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/BooleanType.php',
  'phpcassa\\Schema\\DataType\\BytesType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/BytesType.php',
  'phpcassa\\Schema\\DataType\\CassandraType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/CassandraType.php',
  'phpcassa\\Schema\\DataType\\CompositeType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/CompositeType.php',
  'phpcassa\\Schema\\DataType\\DoubleType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/DoubleType.php',
  'phpcassa\\Schema\\DataType\\FloatType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/FloatType.php',
  'phpcassa\\Schema\\DataType\\IntegerType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/IntegerType.php',
  'phpcassa\\Schema\\DataType\\LexicalUUIDType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/LexicalUUIDType.php',
  'phpcassa\\Schema\\DataType\\LongType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/LongType.php',
  'phpcassa\\Schema\\DataType\\TimeUUIDType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/TimeUUIDType.php',
  'phpcassa\\Schema\\DataType\\UTF8Type' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/UTF8Type.php',
  'phpcassa\\Schema\\DataType\\UUIDType' => __DIR__.'/classes/lib/phpcassa/Schema/DataType/UUIDType.php',
  'phpcassa\\SuperColumnFamily' => __DIR__.'/classes/lib/phpcassa/SuperColumnFamily.php',
  'phpcassa\\SystemManager' => __DIR__.'/classes/lib/phpcassa/SystemManager.php',
  'phpcassa\\Util\\Clock' => __DIR__.'/classes/lib/phpcassa/Util/Clock.php',
  'phpcassa\\UUID\\UUIDException' => __DIR__.'/classes/lib/phpcassa/UUID/UUIDException.php',
  
  // Thrift
  'TType' => __DIR__.'/classes/lib/thrift/Thrift.php',
  'TMessageType' => __DIR__.'/classes/lib/thrift/Thrift.php',
  'TException' => __DIR__.'/classes/lib/thrift/Thrift.php',
  'TBase' => __DIR__.'/classes/lib/thrift/Thrift.php',
  'TApplicationException' => __DIR__.'/classes/lib/thrift/Thrift.php',
  'cassandra\\CassandraIf' => __DIR__.'/classes/lib/thrift/packages/cassandra/Cassandra.php',
  'cassandra\\AuthenticationException' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.AuthenticationException.php',
  'cassandra\\AuthenticationRequest' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.AuthenticationRequest.php',
  'cassandra\\AuthorizationException' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.AuthorizationException.php',
  'cassandra\\CassandraClient' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra.Client.php',
  'cassandra\\Cassandra_add_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_add_args.php',
  'cassandra\\Cassandra_add_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_add_result.php',
  'cassandra\\Cassandra_batch_mutate_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_batch_mutate_args.php',
  'cassandra\\Cassandra_batch_mutate_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_batch_mutate_result.php',
  'cassandra\\Cassandra_describe_cluster_name_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_cluster_name_args.php',
  'cassandra\\Cassandra_describe_cluster_name_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_cluster_name_result.php',
  'cassandra\\Cassandra_describe_keyspaces_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_keyspaces_args.php',
  'cassandra\\Cassandra_describe_keyspaces_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_keyspaces_result.php',
  'cassandra\\Cassandra_describe_keyspace_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_keyspace_args.php',
  'cassandra\\Cassandra_describe_keyspace_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_keyspace_result.php',
  'cassandra\\Cassandra_describe_version_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_version_args.php',
  'cassandra\\Cassandra_describe_partitioner_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_partitioner_args.php',
  'cassandra\\Cassandra_describe_partitioner_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_partitioner_result.php',
  'cassandra\\Cassandra_describe_ring_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_ring_args.php',
  'cassandra\\Cassandra_describe_ring_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_ring_result.php',
  'cassandra\\Cassandra_describe_schema_versions_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_schema_versions_args.php',
  'cassandra\\Cassandra_describe_schema_versions_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_schema_versions_result.php',
  'cassandra\\Cassandra_describe_snitch_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_snitch_args.php',
  'cassandra\\Cassandra_describe_snitch_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_snitch_result.php',
  'cassandra\\Cassandra_describe_splits_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_splits_args.php',
  'cassandra\\Cassandra_describe_splits_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_splits_result.php',
  'cassandra\\Cassandra_describe_version_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_describe_version_result.php',
  'cassandra\\Cassandra_execute_cql_query_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_execute_cql_query_args.php',
  'cassandra\\Cassandra_execute_cql_query_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_execute_cql_query_result.php',
  'cassandra\\Cassandra_execute_prepared_cql_query_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_execute_prepared_cql_query_args.php',
  'cassandra\\Cassandra_execute_prepared_cql_query_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_execute_prepared_cql_query_result.php',
  'cassandra\\Cassandra_get_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_get_args.php',
  'cassandra\\Cassandra_get_count_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_get_count_args.php',
  'cassandra\\Cassandra_get_count_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_get_count_result.php',
  'cassandra\\Cassandra_get_indexed_slices_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_get_indexed_slices_args.php',
  'cassandra\\Cassandra_get_indexed_slices_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_get_indexed_slices_result.php',
  'cassandra\\Cassandra_get_paged_slice_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_get_paged_slice_args.php',
  'cassandra\\Cassandra_get_paged_slice_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_get_paged_slice_result.php',
  'cassandra\\Cassandra_get_range_slices_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_get_range_slices_args.php',
  'cassandra\\Cassandra_get_range_slices_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_get_range_slices_result.php',
  'cassandra\\Cassandra_get_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_get_result.php',
  'cassandra\\Cassandra_get_slice_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_get_slice_args.php',
  'cassandra\\Cassandra_get_slice_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_get_slice_result.php',
  'cassandra\\Cassandra_insert_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_insert_args.php',
  'cassandra\\Cassandra_insert_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_insert_result.php',
  'cassandra\\Cassandra_login_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_login_args.php',
  'cassandra\\Cassandra_login_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_login_result.php',
  'cassandra\\Cassandra_multiget_count_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_multiget_count_args.php',
  'cassandra\\Cassandra_multiget_count_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_multiget_count_result.php',
  'cassandra\\Cassandra_multiget_slice_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_multiget_slice_args.php',
  'cassandra\\Cassandra_multiget_slice_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_multiget_slice_result.php',
  'cassandra\\Cassandra_prepare_cql_query_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_prepare_cql_query_args.php',
  'cassandra\\Cassandra_prepare_cql_query_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_prepare_cql_query_result.php',
  'cassandra\\Cassandra_remove_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_remove_args.php',
  'cassandra\\Cassandra_remove_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_remove_result.php',
  'cassandra\\Cassandra_remove_counter_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_remove_counter_args.php',
  'cassandra\\Cassandra_remove_counter_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_remove_counter_result.php',
  'cassandra\\Cassandra_set_cql_version_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_set_cql_version_args.php',
  'cassandra\\Cassandra_set_cql_version_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_set_cql_version_result.php',
  'cassandra\\Cassandra_set_keyspace_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_set_keyspace_args.php',
  'cassandra\\Cassandra_set_keyspace_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_set_keyspace_result.php',
  'cassandra\\Cassandra_system_add_column_family_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_system_add_column_family_args.php',
  'cassandra\\Cassandra_system_add_column_family_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_system_add_column_family_result.php',
  'cassandra\\Cassandra_system_add_keyspace_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_system_add_keyspace_args.php',
  'cassandra\\Cassandra_system_add_keyspace_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_system_add_keyspace_result.php',
  'cassandra\\Cassandra_system_drop_column_family_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_system_drop_column_family_args.php',
  'cassandra\\Cassandra_system_drop_column_family_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_system_drop_column_family_result.php',
  'cassandra\\Cassandra_system_drop_keyspace_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_system_drop_keyspace_args.php',
  'cassandra\\Cassandra_system_drop_keyspace_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_system_drop_keyspace_result.php',
  'cassandra\\Cassandra_system_update_column_family_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_system_update_column_family_args.php',
  'cassandra\\Cassandra_system_update_column_family_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_system_update_column_family_result.php',
  'cassandra\\Cassandra_system_update_keyspace_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_system_update_keyspace_args.php',
  'cassandra\\Cassandra_system_update_keyspace_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_system_update_keyspace_result.php',
  'cassandra\\Cassandra_truncate_args' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_truncate_args.php',
  'cassandra\\Cassandra_truncate_result' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Cassandra_truncate_result.php',
  'cassandra\\CfDef' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.CfDef.php',
  'cassandra\\Column' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Column.php',
  'cassandra\\ColumnDef' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.ColumnDef.php',
  'cassandra\\ColumnOrSuperColumn' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.ColumnOrSuperColumn.php',
  'cassandra\\ColumnParent' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.ColumnParent.php',
  'cassandra\\ColumnPath' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.ColumnPath.php',
  'cassandra\\CounterColumn' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.CounterColumn.php',
  'cassandra\\CounterSuperColumn' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.CounterSuperColumn.php',
  'cassandra\\CqlMetadata' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.CqlMetadata.php',
  'cassandra\\CqlPreparedResult' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.CqlPreparedResult.php',
  'cassandra\\CqlResult' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.CqlResult.php',
  'cassandra\\CqlRow' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.CqlRow.php',
  'cassandra\\Deletion' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Deletion.php',
  'cassandra\\EndpointDetails' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.EndpointDetails.php',
  'cassandra\\IndexClause' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.IndexClause.php',
  'cassandra\\IndexExpression' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.IndexExpression.php',
  'cassandra\\InvalidRequestException' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.InvalidRequestException.php',
  'cassandra\\KeyCount' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.KeyCount.php',
  'cassandra\\KeyRange' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.KeyRange.php',
  'cassandra\\KeySlice' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.KeySlice.php',
  'cassandra\\KsDef' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.KsDef.php',
  'cassandra\\Mutation' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.Mutation.php',
  'cassandra\\NotFoundException' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.NotFoundException.php',
  'cassandra\\SchemaDisagreementException' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.SchemaDisagreementException.php',
  'cassandra\\SlicePredicate' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.SlicePredicate.php',
  'cassandra\\SliceRange' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.SliceRange.php',
  'cassandra\\SuperColumn' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.SuperColumn.php',
  'cassandra\\TimedOutException' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.TimedOutException.php',
  'cassandra\\TokenRange' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.TokenRange.php',
  'cassandra\\UnavailableException' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra.UnavailableException.php',
  'cassandra\\ConsistencyLevel' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra_constants.php',
  'cassandra\\ConsistencyLevel' => __DIR__.'/classes/lib/thrift/packages/cassandra/cassandra_types.php',
));
